// SPDX-License-Identifier: LicenseRef-Ezurio-Clause
//
// This file is generated by bindgen 0.72.1 from SWUpdate headers.
// Refresh it from bindgen output when updating the supported SWUpdate ABI.

pub const PROGRESS_API_MAJOR: u32 = 2;
pub const PROGRESS_API_MINOR: u32 = 0;
pub const PROGRESS_API_PATCH: u32 = 0;
pub const PROGRESS_API_VERSION: u32 = 131072;
pub const IPC_MAGIC: u32 = 335880193;
pub const SWUPDATE_API_VERSION: u32 = 1;

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum RecoveryStatus {
    IDLE = 0,
    START = 1,
    RUN = 2,
    SUCCESS = 3,
    FAILURE = 4,
    DOWNLOAD = 5,
    DONE = 6,
    SUBPROCESS = 7,
    PROGRESS = 8,
}

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum SourceType {
    SOURCE_UNKNOWN = 0,
    SOURCE_WEBSERVER = 1,
    SOURCE_SURICATTA = 2,
    SOURCE_DOWNLOADER = 3,
    SOURCE_LOCAL = 4,
    SOURCE_CHUNKS_DOWNLOADER = 5,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ProgressMsg {
    pub apiversion: u32,
    pub status: u32,
    pub dwl_percent: u32,
    pub dwl_bytes: ::std::os::raw::c_ulonglong,
    pub nsteps: u32,
    pub cur_step: u32,
    pub cur_percent: u32,
    pub cur_image: [::std::os::raw::c_char; 256],
    pub hnd_name: [::std::os::raw::c_char; 64],
    pub source: u32,
    pub infolen: u32,
    pub info: [::std::os::raw::c_char; 2048],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ProgressConnectAck {
    pub apiversion: u32,
    pub magic: [::std::os::raw::c_char; 4],
}

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum MsgType {
    REQ_INSTALL = 0,
    ACK = 1,
    NACK = 2,
    GET_STATUS = 3,
    POST_UPDATE = 4,
    SWUPDATE_SUBPROCESS = 5,
    SET_AES_KEY = 6,
    SET_UPDATE_STATE = 7,
    GET_UPDATE_STATE = 8,
    REQ_INSTALL_EXT = 9,
    SET_VERSIONS_RANGE = 10,
    NOTIFY_STREAM = 11,
    GET_HW_REVISION = 12,
    SET_SWUPDATE_VARS = 13,
    GET_SWUPDATE_VARS = 14,
    SET_DELTA_URL = 15,
}

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Command {
    CMD_ACTIVATION = 0,
    CMD_CONFIG = 1,
    CMD_ENABLE = 2,
    CMD_GET_STATUS = 3,
    CMD_SET_DOWNLOAD_URL = 4,
}

pub const CMD_ACTIVATION: Command = Command::CMD_ACTIVATION;
pub const CMD_CONFIG: Command = Command::CMD_CONFIG;
pub const CMD_ENABLE: Command = Command::CMD_ENABLE;
pub const CMD_GET_STATUS: Command = Command::CMD_GET_STATUS;
pub const CMD_SET_DOWNLOAD_URL: Command = Command::CMD_SET_DOWNLOAD_URL;

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum RunType {
    RUN_DEFAULT = 0,
    RUN_DRYRUN = 1,
    RUN_INSTALL = 2,
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct SwupdateRequest {
    pub apiversion: ::std::os::raw::c_uint,
    pub source: SourceType,
    pub dry_run: RunType,
    pub len: usize,
    pub info: [::std::os::raw::c_char; 512],
    pub software_set: [::std::os::raw::c_char; 256],
    pub running_mode: [::std::os::raw::c_char; 256],
    pub disable_store_swu: bool,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub union MsgData {
    pub msg: [::std::os::raw::c_char; 128],
    pub status: StatusMsg,
    pub notify: NotifyMsg,
    pub instmsg: InstallMsg,
    pub procmsg: ProcessMsg,
    pub aeskeymsg: AesKeyMsg,
    pub versions: VersionsMsg,
    pub revisions: RevisionsMsg,
    pub vars: VariablesMsg,
    pub dwl_url: DownloadUrlMsg,
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct StatusMsg {
    pub current: ::std::os::raw::c_int,
    pub last_result: ::std::os::raw::c_int,
    pub error: ::std::os::raw::c_int,
    pub desc: [::std::os::raw::c_char; 2048],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct NotifyMsg {
    pub status: ::std::os::raw::c_int,
    pub error: ::std::os::raw::c_int,
    pub level: ::std::os::raw::c_int,
    pub msg: [::std::os::raw::c_char; 2048],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct InstallMsg {
    pub req: SwupdateRequest,
    pub len: ::std::os::raw::c_uint,
    pub buf: [::std::os::raw::c_char; 2048],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ProcessMsg {
    pub source: SourceType,
    pub cmd: ::std::os::raw::c_int,
    pub timeout: ::std::os::raw::c_int,
    pub len: ::std::os::raw::c_uint,
    pub buf: [::std::os::raw::c_char; 2048],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct AesKeyMsg {
    pub key_ascii: [::std::os::raw::c_char; 65],
    pub ivt_ascii: [::std::os::raw::c_char; 33],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct VersionsMsg {
    pub minimum_version: [::std::os::raw::c_char; 256],
    pub maximum_version: [::std::os::raw::c_char; 256],
    pub current_version: [::std::os::raw::c_char; 256],
    pub update_type: [::std::os::raw::c_char; 256],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct RevisionsMsg {
    pub boardname: [::std::os::raw::c_char; 256],
    pub revision: [::std::os::raw::c_char; 256],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct VariablesMsg {
    pub varnamespace: [::std::os::raw::c_char; 256],
    pub varname: [::std::os::raw::c_char; 256],
    pub varvalue: [::std::os::raw::c_char; 256],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct DownloadUrlMsg {
    pub filename: [::std::os::raw::c_char; 256],
    pub url: [::std::os::raw::c_char; 1024],
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct IpcMessage {
    pub magic: ::std::os::raw::c_int,
    pub type_: ::std::os::raw::c_int,
    pub data: MsgData,
}
