[package]
name = "summit-usbgadget-swupdate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "SWUpdate transport, status, and runtime system-information support for summit-usbgadget"
license.workspace = true

[dependencies]
bytes.workspace = true
futures-util.workspace = true
log.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
swupdate-ipc.workspace = true
tokio.workspace = true

[lints]
workspace = true
