[source.crates-io]
registry = "sparse+https://index.crates.io/"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

#[resolver]
#incompatible-rust-versions = "fallback"
