[package]
name = "summit-usbgadget-fastboot-usb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "fastboot-usb upload protocol implementation and config schema for summit-usbgadget"
license.workspace = true

[dependencies]
bytes.workspace = true
log.workspace = true
rustix.workspace = true
serde.workspace = true
summit-usbgadget-fastboot-proto.workspace = true
summit-usbgadget-swupdate.workspace = true
summit-usbgadget-usb.workspace = true
tokio.workspace = true
usb-gadget.workspace = true

[lints]
workspace = true

[dev-dependencies]
nusb.workspace = true